In [9]:
import os
import pandas as pd

# Specify the folder containing the CSV files
folder_path = r"C:\Users\Richard\Documents\We Cloud Data\Business Development\public biz dev\biz_dev_public\Full workflow Indeed\job_details_Indeed"

# List to hold dataframes
dataframes = []

# Function to extract the search keyword from the filename
def extract_search_keyword(filename):
    # Split by underscore and take the third element
    parts = filename.split('_')
    # Join all parts after the second underscore until the last underscore
    keyword = '_'.join(parts[2:-1]).replace('.csv', '')
    return keyword.replace('_', ' ')

# Iterate through all files in the folder
for file in os.listdir(folder_path):
    if file.endswith('.csv'):
        file_path = os.path.join(folder_path, file)
        # Read each CSV file
        df = pd.read_csv(file_path)
        # Extract the search keyword and add it as a new column
        df['Search Keyword'] = extract_search_keyword(file)
        # Append the dataframe to the list
        dataframes.append(df)

# Concatenate all dataframes
combined_df = pd.concat(dataframes, ignore_index=True)

# Save the combined dataframe to a new CSV file (optional)
output_path = os.path.join(folder_path, 'combined_job_details_with_keywords.csv')
combined_df.to_csv(output_path, index=False)

print(f"Combined CSV with search keywords saved to: {output_path}")

Combined CSV with search keywords saved to: C:\Users\Richard\Documents\We Cloud Data\Business Development\public biz dev\biz_dev_public\Full workflow Indeed\job_details_Indeed\combined_job_details_with_keywords.csv

In [10]:
combined_df

,name,key,title,location,jobType,posted,days_ago,rating,experience,salary,...,feed,link,Tools,Soft Skills,Industry Skills,description,Search Keyword,date,chunk,Data Jobs Keywords
0,GSK,a2abe316ba63c9e4,Medical Representative Jeddah,Saudi Arabia,NaN,Just posted,0.0,4.1,[],[],...,https://jobs.gsk.com/jobs/402969?lang=en-us&so...,https://indeed.com/cmp/Gsk-5f077e22,['powerpoint'],"['focus', 'planning', 'reliable', 'accountabil...",[],site name: field worker - sau posted date: sep...,business intelligence,NaN,NaN,NaN
1,Aram Meem,7ad9c6248aadd7ca,Business Development Manager /Sales ( For Saud...,Dammam,Full-time,Just posted,0.0,2.5,['1-2'],[],...,https://toyou.bamboohr.com/careers/94?source=i...,https://indeed.com/cmp/Aram-Meem,[],"['confidence', 'coaching', 'organization', 'ne...",[],toyou is a leading online saudi food ordering ...,business intelligence,NaN,NaN,NaN
2,NTT DATA,d75c2c8a3260d80d,NOC Engineer L1,Riyadh,Full-time,Just posted,0.0,3.5,[],[],...,https://careers.services.global.ntt/global/en/...,https://indeed.com/cmp/Ntt-Data,['python'],"['communication skills', 'ownership', 'communi...","['transform', 'scripting', 'monitoring']",make an impact with ntt data join a company th...,business intelligence,NaN,NaN,NaN
3,"Marriott International, Inc",97e48178294b24ae,Corporate Sales Executive,Riyadh,NaN,Just posted,0.0,4.0,['2'],[],...,https://jobs.marriott.com/jobs/24154343?lang=e...,https://indeed.com/cmp/Marriott-International,[],"['focus', 'leadership', 'research', 'prioritiz...",['business intelligence'],job number 24154343 job category sales &amp; m...,business intelligence,NaN,NaN,NaN
4,Aram Meem,a37a355463e5cd93,Lead Product Manager,Riyadh,Full-time,Just posted,0.0,2.5,['5'],[],...,https://toyou.bamboohr.com/careers/326?source=...,https://indeed.com/cmp/Aram-Meem,['jira'],"['innovation', 'planning', 'analysis', 'design']","['data analysis', 'statistics']",toyou is a leading online saudi food ordering ...,business intelligence,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8940,PASQAL,97061ccc96a721c3,Quantum Technical Sales Engineer - Middle East...,Thuwal,NaN,30+ days ago,30.0,NaN,['3+'],[],...,https://careers.pasqal.com/jobs/4544689-quantu...,https://indeed.com/cmp/Pasqal,['python'],"['communication skills', 'analysis', 'design',...","['machine learning', 'metrics']","quantum technical sales engineer- middle east,...",machine learning engineer,NaN,NaN,NaN
8941,Lucidya,c36561c46dc00422,Technical Internship or Coop,Riyadh,Full-time,30+ days ago,30.0,NaN,[],[],...,https://apply.workable.com/j/633F3466A6,https://indeed.com/cmp/Lucidya,[],['innovation'],"['machine learning', 'big data']",we are looking for interns or coop students to...,machine learning engineer,NaN,NaN,NaN
8942,aramcoservices,4c01a8b9893f9fe4,Generative AI Expert,Saudi Arabia,NaN,30+ days ago,30.0,NaN,['5+'],[],...,https://careers.aramco.com/expat_us/job/Genera...,https://indeed.com/cmp/Aramcoservices,['python'],"['discipline', 'responsible', 'organization', ...","['nlp', 'deep learning', 'ml', 'machine learni...",job req id: 13968 description: aramco energize...,machine learning engineer,NaN,NaN,NaN
8943,webook.com,c6d6d4ddfa8f68cd,Data Engineer,Riyadh,Full-time,30+ days ago,30.0,NaN,['5-6'],[],...,https://www.careers-page.com/supertech-2/job/L...,https://indeed.com/cmp/Webook.com,"['sql', 'cloud', 'java', 'mongodb', 'tableau',...","['organization', 'planning', 'design', 'agilit...","['devops', 'cloud computing', 'data ingestion'...",do you want to love what you do at work? do yo...,machine learning engineer,NaN,NaN,NaN
8944,webook.com,1ee26161fe8743b5,Machine Learning Engineer,Riyadh,Full-time,30+ days ago,30.0,NaN,[],[],...,https://www.careers-page.com/supertech-2/job/L...,https://indeed.com/cmp/Webook.com,"['tensorflow', 'llms', 'cloud', 'java', 'pytor...","['communication skills', 'design', 'agility', ...","['deep learning', 'llms', 'cloud', 'natural la...",do you want to love what you do at work? do yo...,machine learning engineer,NaN,NaN,NaN

In [11]:
import re

In [25]:
tools = ["AWS", "MS Access", "Microsoft Access", "Azure", " C ", " C,", "C++", "Cassandra", "CircleCI", "Cloud", "Confluence", "Databricks", "Docker", "EMR", "ElasticSearch",
        " Excel ", "Flask", "MLFlow", "Kubeflow", "GCP", " Git ", "Github", "Hadoop", "Hive", "Hugging Face", "Informatica", "JIRA", "Java", "Javascript",
        "Jenkins", "Kafka", "Keras", "Kubernetes", "LLMs", "Matlab", "Mongodb", "MySQL", "New Relic", "NoSQL", "Numpy", "Oracle", "Outlook",
        "Pandas", "PostgreSQL", "Postman", "Power BI", "PowerPoint", "PySpark", "Python", "Pytorch", "Quicksight", " R ", " R, ", "Redshift", "S3",
        "SAP", "SAS", "SOAP", "SPSS", "SQL", "SQL Server", "Scala", "Scikit-learn", "Snowflake", "Spacy", "Spark", "StreamLit", "Tableau",
        "Talend", "Tensorflow", "Terraform", "Torch", "VBA", " Word ", "XML", "transformer", "CI/CD"]
industry_skills = ["API Design", "API Development", "Batch Processing", "Big data", "Bioinformatics", "Business Intelligence", "CI/CD",
                "Classification", "Cloud", "Cloud Computing", "Containerization", "Critical Thinking", "Data Analysis",
                "Data Architecture", "Data Cleaning", "Data Extraction", "Data Governance", "Data Ingestion", "Data Integration",
                "Data Manipulation", "Data Mining", "Data Modeling", "Data Pipelines", "Data Security", "Data Visualization",
                "Data Warehousing", "Data Wrangling", "Database Design", "Deep Learning", "DevOps", "Distributed computing", "ETL",
                "Econometrics", "Extract", "Feature Engineering", "Google Cloud", "Kubernetes", "LLMs", "Load (ETL) Processes",
                "Logging", "ML", "Machine Learning", "Mathematics", "Metrics", "Microservices Architecture", "Model Deployment",
                "Model Monitoring", "NLP", "Natural Language Processing", "Natural Language Understanding",
                "Report Generation", "Research Skills",
                "Scripting", "Statistical Analysis", "Statistics", "Technical Documentation", 
                "Understanding of Machine Learning Algorithms"]

In [26]:
lowercase_keywords = [keyword.lower() for keyword in tools + industry_skills]

# Create a regex pattern for the lowercase keywords
regex_pattern = r'\b(?:' + '|'.join(re.escape(keyword.strip()) for keyword in lowercase_keywords) + r')\b'

combined_df['Match Keywords'] = combined_df['description'].apply(
    lambda x: ', '.join(sorted(set(re.findall(regex_pattern, x.lower())))) if pd.notnull(x) else ''
)

In [23]:
combined_df.columns

Index(['name', 'key', 'title', 'location', 'jobType', 'posted', 'days_ago',
       'rating', 'experience', 'salary', 'education', 'feed', 'link', 'Tools',
       'Soft Skills', 'Industry Skills', 'description', 'Search Keyword',
       'date', 'chunk', 'Data Jobs Keywords', 'Match Keywords'],
      dtype='object')

In [27]:
combined_df[['description', 'Match Keywords']].head()

,description,Match Keywords
0,site name: field worker - sau posted date: sep...,"excel, powerpoint, word"
1,toyou is a leading online saudi food ordering ...,excel
2,make an impact with ntt data join a company th...,"python, r, scripting"
3,job number 24154343 job category sales &amp; m...,business intelligence
4,toyou is a leading online saudi food ordering ...,"data analysis, jira, statistics"

In [29]:
combined_df['Number of Matching Keywords'] = combined_df['Match Keywords'].apply(
    lambda x: len(x.split(', ')) if x else 0
)

In [31]:
combined_df.to_csv("updated_combined_df_with_keyword_count.csv", index=False)

## Final Script

In [ ]:
import os
import pandas as pd
import re

# Function to extract search keyword and date from filename
def extract_details_from_filename(filename):
    parts = filename.split('_')
    search_keyword = '_'.join(parts[2:-1]).replace('.csv', '').replace('_', ' ')
    date_match = re.search(r'\d{4}-\d{2}-\d{2}', filename)
    date = date_match.group(0) if date_match else None
    return search_keyword, date

# Function to concatenate all CSV files with extracted details
def concatenate_csv_files(folder_path):
    dataframes = []
    for file in os.listdir(folder_path):
        if file.endswith('.csv'):
            file_path = os.path.join(folder_path, file)
            search_keyword, date = extract_details_from_filename(file)
            df = pd.read_csv(file_path)
            df['Search Keyword'] = search_keyword
            df['Date'] = date
            dataframes.append(df)
    combined_df = pd.concat(dataframes, ignore_index=True)
    return combined_df

# Function to match keywords in the 'description' column
def match_keywords(df, tools, industry_skills):
    lowercase_keywords = [keyword.lower() for keyword in tools + industry_skills]
    regex_pattern = r'\b(?:' + '|'.join(re.escape(keyword.strip()) for keyword in lowercase_keywords) + r')\b'
    df['Match Keywords'] = df['description'].apply(
        lambda x: ', '.join(sorted(set(re.findall(regex_pattern, x.lower())))) if pd.notnull(x) else ''
    )
    return df

# Function to count the number of matching keywords
def count_keywords(df):
    df['Number of Matching Keywords'] = df['Match Keywords'].apply(
        lambda x: len(x.split(', ')) if x else 0
    )
    return df

# Main function to run the entire process
if __name__ == "__main__":
    # Define folder path and keywords
    folder_path = r"C:\Users\Richard\Documents\We Cloud Data\Business Development\public biz dev\biz_dev_public\Full workflow Indeed\job_details_Indeed"
    tools = ["AWS", "MS Access", "Microsoft Access", "Azure", " C ", " C,", "C++", "Cassandra", "CircleCI", "Cloud", "Confluence", "Databricks", "Docker", "EMR", "ElasticSearch",
        " Excel ", "Flask", "MLFlow", "Kubeflow", "GCP", " Git ", "Github", "Hadoop", "Hive", "Hugging Face", "Informatica", "JIRA", "Java", "Javascript",
        "Jenkins", "Kafka", "Keras", "Kubernetes", "LLMs", "Matlab", "Mongodb", "MySQL", "New Relic", "NoSQL", "Numpy", "Oracle",
        "Pandas", "PostgreSQL", "Postman", "Power BI", "PySpark", "Python", "Pytorch", "Quicksight", " R ", " R, ", "Redshift", "S3",
        "SAP", "SAS","SQL", "SQL Server", "Scala", "Scikit-learn", "Snowflake", "Spacy", "Spark", "StreamLit", "Tableau",
        "Talend", "Tensorflow", "Terraform", "Torch", "VBA", "XML", "transformer", "CI/CD"]
    industry_skills = ["API Design", "API Development", "Batch Processing", "Big data", "Bioinformatics", "Business Intelligence", "CI/CD",
                "Classification", "Cloud", "Cloud Computing", "Containerization", "Critical Thinking", "Data Analysis",
                "Data Architecture", "Data Cleaning", "Data Extraction", "Data Governance", "Data Ingestion", "Data Integration",
                "Data Manipulation", "Data Mining", "Data Modeling", "Data Pipelines", "Data Security", "Data Visualization",
                "Data Warehousing", "Data Wrangling", "Database Design", "Deep Learning", "DevOps", "Distributed computing", "ETL",
                "Econometrics", "Extract", "Feature Engineering", "Google Cloud", "Kubernetes", "LLMs", "Load (ETL) Processes",
                "Logging", "ML", "Machine Learning", "Mathematics", "Metrics", "Microservices Architecture", "Model Deployment",
                "Model Monitoring", "NLP", "Natural Language Processing", "Natural Language Understanding",
                "Report Generation", "Research Skills",
                "Scripting", "Statistical Analysis", "Statistics", "Technical Documentation", 
                "Understanding of Machine Learning Algorithms"]

    # Process the CSV files
    combined_df = concatenate_csv_files(folder_path)
    combined_df = match_keywords(combined_df, tools, industry_skills)
    combined_df = count_keywords(combined_df)

    column_order= ['Date','Search Keyword','Match Keywords','Number of Matching Keywords','name', 'key', 'title', 'location', 'jobType', 'posted', 'days_ago',
       'rating', 'experience', 'salary', 'education', 'feed', 'link', 'Tools',
       'Soft Skills', 'Industry Skills', 'description' ]

    # Save the final DataFrame to a CSV file
    output_path = os.path.join('final_combined_job_details.csv')
    combined_df[column_order].to_csv(output_path, index=False)
    print(f"Final combined CSV saved to: {output_path}")

Final combined CSV saved to: final_combined_job_details.csv

In [38]:
combined_df.columns

Index(['name', 'key', 'title', 'location', 'jobType', 'posted', 'days_ago',
       'rating', 'experience', 'salary', 'education', 'feed', 'link', 'Tools',
       'Soft Skills', 'Industry Skills', 'description', 'Search Keyword',
       'Date', 'date', 'chunk', 'Data Jobs Keywords', 'Match Keywords',
       'Number of Matching Keywords'],
      dtype='object')